export const tags = [
	"art",
	"digital",
	"creative",
	"illustration",
	"design",
	"modern",
	"unique",
	"gallery",
	"imagination",
	"expression",
	"colorful",
	"digitalart",
	"collection",
	"artist",
	"artistic",
	"coding",
	"programming",
	"javascript",
	"python",
	"codingadventures",
	"code",
	"webdevelopment",
	"codingcommunity",
	"ebook",
	"learntocode",
	"codinglife",
	"development",
	"technology",
	"codingtips",
	"software",
	"music",
	"album",
	"harmony",
	"melody",
	"sound",
	"musical",
	"waves",
	"composition",
	"instrumental",
	"audio",
	"melodic",
	"musician",
	"harmonicwaves",
	"artist",
	"musiclover",
	"photography",
	"photo",
	"capture",
	"snapshot",
	"photographer",
	"bundle",
	"picture",
	"moment",
	"visual",
	"artistic",
	"gallery",
	"creative",
	"photograph",
	"collection",
	"image",
	"scifi",
	"sciencefiction",
	"adventure",
	"ebook",
	"space",
	"future",
	"exploration",
	"aliens",
	"technology",
	"imagination",
	"science",
	"fiction",
	"author",
	"book",
	"adventures",
	"webdevelopment",
	"html",
	"css",
	"codingcourse",
	"codingtutorial",
	"webdesign",
	"programming",
	"code",
	"frontend",
	"webdeveloper",
	"htmlcss",
	"webdev",
	"tutorial",
	"webmaster",
	"coding",
	"digitalmarketing",
	"marketing",
	"onlinepresence",
	"guide",
	"branding",
	"socialmedia",
	"strategy",
	"digitalstrategy",
	"marketingtips",
	"business",
	"onlinebranding",
	"promotion",
	"guidebook",
	"marketingexpert",
	"brandboost",
	"cooking",
	"culinary",
	"cookbook",
	"recipes",
	"chef",
	"food",
	"delicious",
	"cuisine",
	"gourmet",
	"flavorful",
	"homemade",
	"foodie",
	"kitchen",
	"culinaryarts",
	"tasty",
	"fitness",
	"healthyliving",
	"workout",
	"exercise",
	"wellness",
	"guide",
	"fitlife",
	"health",
	"nutrition",
	"fitnesstips",
	"body",
	"fitnessjourney",
	"healthyhabits",
	"lifestyle",
	"wellbeing",
	"travel",
	"photography",
	"wanderlust",
	"worldwonders",
	"explore",
	"adventure",
	"collection",
	"travelphotographer",
	"visualjourney",
	"landscape",
	"wondersoftheworld",
	"photocollection",
	"discover",
	"globetrotter",
	"languagelearning",
	"polyglot",
	"languages",
	"linguistics",
	"bundle",
	"multilingual",
	"languagecourse",
	"linguist",
	"communication",
	"multilanguage",
	"languagestudy",
	"polyglotism",
	"linguisticbundle",
	"learnlanguages",
	"communication",
	"selfcare",
	"wellness",
	"mindfulness",
	"guide",
	"health",
	"mentalhealth",
	"bodycare",
	"relaxation",
	"wellnessguru",
	"zen",
	"stressrelief",
	"mindbodysoul",
	"mindful",
	"holistic",
	"wellbeing",
	"fashion",
	"fashiondesign",
	"style",
	"course",
	"design",
	"creativity",
	"fashionista",
	"clothing",
	"trendy",
	"expressyourself",
	"creativeexpression",
	"designcourse",
	"fashionlover",
	"stylish",
	"couture",
	"languagelearning",
	"polyglot",
	"languages",
	"linguistics",
	"bundle",
	"multilingual",
	"languagecourse",
	"linguist",
	"communication",
	"multilanguage",
	"languagestudy",
	"polyglotism",
	"linguisticbundle",
	"learnlanguages",
	"communication",
];

export const categories = [
	"Digital Art",
	"Programming",
	"Music",
	"Photography",
	"Science Fiction",
	"Web Development",
	"Digital Marketing",
	"Cooking",
	"Fitness",
	"Travel",
	"Language Learning",
	"Wellness",
	"Fashion",
	"Health & Wellness",
	"Software Development",
];

export const products = [
	{
		id: 1,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Digital Art Collection",
		author: {
			authorName: "CreativeArtist123",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "123 Art Street, Imaginaria",
		},
		category: "Digital Art",
		date: "2024-02-03",
		price: 19.99,
		description:
			"Explore a stunning collection of digital artworks created by CreativeArtist123. Each piece is a unique expression of creativity.",
		tags: [
			"art",
			"digital",
			"creative",
			"illustration",
			"design",
			"modern",
			"unique",
			"gallery",
			"imagination",
			"expression",
			"colorful",
			"digitalart",
			"collection",
			"artist",
			"artistic",
		],
		status: "Pending",
	},
	{
		id: 2,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Ebook: Coding Adventures",
		author: {
			authorName: "CodeExplorer789",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "789 Code Lane, Algorithm City",
		},
		category: "Programming",
		date: "2024-02-05",
		price: 14.99,
		description:
			"Embark on coding adventures with this comprehensive ebook by CodeExplorer789. Learn new programming techniques and improve your coding skills.",
		tags: [
			"coding",
			"programming",
			"javascript",
			"python",
			"codingadventures",
			"code",
			"webdevelopment",
			"codingcommunity",
			"ebook",
			"learntocode",
			"codinglife",
			"development",
			"technology",
			"codingtips",
			"software",
		],
		status: "Approved",
	},
	{
		id: 3,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Music Album: Harmonic Waves",
		author: {
			authorName: "MelodyMaestro456",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "456 Melody Street, Harmony Town",
		},
		category: "Music",
		date: "2024-02-08",
		price: 24.99,
		description:
			"Immerse yourself in the soothing melodies of Harmonic Waves, a music album crafted by MelodyMaestro456. Experience a journey through various musical genres.",
		tags: [
			"music",
			"album",
			"harmony",
			"melody",
			"sound",
			"musical",
			"waves",
			"composition",
			"instrumental",
			"audio",
			"melodic",
			"musician",
			"harmonicwaves",
			"artist",
			"musiclover",
		],
		status: "Denied",
	},
	{
		id: 4,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Photography Bundle: Captured Moments",
		author: {
			authorName: "SnapshotMaster789",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "789 Shutter Street, Pictureville",
		},
		category: "Photography",
		date: "2024-02-10",
		price: 29.99,
		description:
			"Discover a stunning collection of high-quality photographs in the Captured Moments bundle by SnapshotMaster789. Each image tells a unique story.",
		tags: [
			"photography",
			"photo",
			"capture",
			"snapshot",
			"photographer",
			"bundle",
			"picture",
			"moment",
			"visual",
			"artistic",
			"gallery",
			"creative",
			"photograph",
			"collection",
			"image",
		],
		status: "Approved",
	},
	{
		id: 5,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Ebook: Sci-Fi Adventures",
		author: {
			authorName: "SciFiExplorer456",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "456 Future Lane, Sci-Fi City",
		},
		category: "Science Fiction",
		date: "2024-02-12",
		price: 16.99,
		description:
			"Embark on thrilling sci-fi adventures with this captivating ebook by SciFiExplorer456. Dive into futuristic worlds and explore the unknown.",
		tags: [
			"scifi",
			"sciencefiction",
			"adventure",
			"ebook",
			"space",
			"future",
			"exploration",
			"aliens",
			"technology",
			"imagination",
			"science",
			"fiction",
			"author",
			"book",
			"adventures",
		],
		status: "Pending",
	},
	{
		id: 6,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Web Development Course: Mastering HTML & CSS",
		author: {
			authorName: "CodeMaster789",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "789 Code Lane, Webville",
		},
		category: "Web Development",
		date: "2024-02-15",
		price: 49.99,
		description:
			"Learn the essentials of web development with this comprehensive course by CodeMaster789. Master HTML and CSS to build stunning websites.",
		tags: [
			"webdevelopment",
			"html",
			"css",
			"codingcourse",
			"codingtutorial",
			"webdesign",
			"programming",
			"code",
			"frontend",
			"webdeveloper",
			"htmlcss",
			"webdev",
			"tutorial",
			"webmaster",
			"coding",
		],
		status: "Denied",
	},
	{
		id: 7,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Digital Marketing Guide: Boost Your Online Presence",
		author: {
			authorName: "MarketingPro123",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "123 Market Street, BrandCity",
		},
		category: "Digital Marketing",
		date: "2024-02-18",
		price: 34.99,
		description:
			"Enhance your online presence with this comprehensive digital marketing guide by MarketingPro123. Learn proven strategies to boost your brand.",
		tags: [
			"digitalmarketing",
			"marketing",
			"onlinepresence",
			"guide",
			"branding",
			"socialmedia",
			"strategy",
			"digitalstrategy",
			"marketingtips",
			"business",
			"onlinebranding",
			"promotion",
			"guidebook",
			"marketingexpert",
			"brandboost",
		],
		status: "Pending",
	},
	{
		id: 8,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Cookbook: Culinary Delights",
		author: {
			authorName: "GourmetChef456",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "456 Culinary Lane, Flavorville",
		},
		category: "Cooking",
		date: "2024-02-20",
		price: 19.99,
		description:
			"Explore the world of culinary delights with this exquisite cookbook by GourmetChef456. Discover mouth-watering recipes and culinary secrets.",
		tags: [
			"cooking",
			"culinary",
			"cookbook",
			"recipes",
			"chef",
			"food",
			"delicious",
			"cuisine",
			"gourmet",
			"flavorful",
			"homemade",
			"foodie",
			"kitchen",
			"culinaryarts",
			"tasty",
		],
		status: "Approved",
	},

	{
		id: 9,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Fitness Guide: Healthy Living Journey",
		author: {
			authorName: "FitLifestyle789",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "789 Wellness Street, FitCity",
		},
		category: "Fitness",
		date: "2024-02-23",
		price: 24.99,
		description:
			"Embark on a journey to a healthier lifestyle with this fitness guide by FitLifestyle789. Discover effective workout routines and nutrition tips.",
		tags: [
			"fitness",
			"healthyliving",
			"workout",
			"exercise",
			"wellness",
			"guide",
			"fitlife",
			"health",
			"nutrition",
			"fitnesstips",
			"body",
			"fitnessjourney",
			"healthyhabits",
			"lifestyle",
			"wellbeing",
		],
		status: "Denied",
	},
	{
		id: 10,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Travel Photography Collection: World Wonders",
		author: {
			authorName: "WanderlustExplorer123",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "123 Explorer Avenue, Wanderland",
		},
		category: "Travel",
		date: "2024-02-26",
		price: 39.99,
		description:
			"Embark on a visual journey around the world with this stunning travel photography collection by WanderlustExplorer123. Explore iconic world wonders through captivating images.",
		tags: [
			"travel",
			"photography",
			"wanderlust",
			"worldwonders",
			"explore",
			"adventure",
			"collection",
			"travelphotographer",
			"visualjourney",
			"landscape",
			"wondersoftheworld",
			"photocollection",
			"discover",
			"globetrotter",
		],
		status: "Approved",
	},
	{
		id: 11,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Language Learning Bundle: Master Multiple Languages",
		author: {
			authorName: "PolyglotMaster789",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "789 Linguistics Lane, Polyglot City",
		},
		category: "Language Learning",
		date: "2024-02-29",
		price: 44.99,
		description:
			"Become a polyglot with this language learning bundle by PolyglotMaster789. Master multiple languages and unlock new opportunities.",
		tags: [
			"languagelearning",
			"polyglot",
			"languages",
			"linguistics",
			"bundle",
			"multilingual",
			"languagecourse",
			"linguist",
			"communication",
			"multilanguage",
			"languagestudy",
			"polyglotism",
			"linguisticbundle",
			"learnlanguages",
			"communication",
		],
		status: "Pending",
	},
	{
		id: 12,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Self-Care Guide: Nurturing Your Mind and Body",
		author: {
			authorName: "WellnessGuru456",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "456 Serenity Street, ZenVille",
		},
		category: "Wellness",
		date: "2024-03-02",
		price: 29.99,
		description:
			"Prioritize self-care with this comprehensive guide by WellnessGuru456. Nurture your mind and body with practical tips and mindful practices.",
		tags: [
			"selfcare",
			"wellness",
			"mindfulness",
			"guide",
			"health",
			"mentalhealth",
			"bodycare",
			"relaxation",
			"wellnessguru",
			"zen",
			"stressrelief",
			"mindbodysoul",
			"mindful",
			"holistic",
			"wellbeing",
		],
		status: "Denied",
	},
	{
		id: 13,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Fashion Design Course: Unleash Your Creativity",
		author: {
			authorName: "Fashionista123",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "123 Style Avenue, FashionCity",
		},
		category: "Fashion",
		date: "2024-03-05",
		price: 54.99,
		description:
			"Discover the world of fashion design with this engaging course by Fashionista123. Unleash your creativity and express your unique style.",
		tags: [
			"fashion",
			"fashiondesign",
			"style",
			"course",
			"design",
			"creativity",
			"fashionista",
			"clothing",
			"trendy",
			"expressyourself",
			"creativeexpression",
			"designcourse",
			"fashionlover",
			"stylish",
			"couture",
		],
		status: "Pending",
	},
	{
		id: 14,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Digital Course: Photography Fundamentals",
		author: {
			authorName: "PhotoEnthusiast789",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "789 Shutter Lane, PhotoCity",
		},
		category: "Photography",
		date: "2024-03-08",
		price: 39.99,
		description:
			"Master the fundamentals of photography with this comprehensive digital course by PhotoEnthusiast789. Learn essential techniques and improve your photography skills.",
		tags: [
			"photography",
			"course",
			"fundamentals",
			"digitalcourse",
			"photoenthusiast",
			"photographyeducation",
			"learning",
			"phototechniques",
			"skillbuilding",
			"visualart",
			"photo",
			"photographer",
			"education",
			"digitallearning",
			"camera",
		],
		status: "Approved",
	},
	{
		id: 15,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Health and Wellness Ebook: Holistic Living",
		author: {
			authorName: "WellnessGuide123",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "123 Serenity Street, WellnessVille",
		},
		category: "Health & Wellness",
		date: "2024-03-11",
		price: 18.99,
		description:
			"Embark on a journey of holistic living with this health and wellness ebook by WellnessGuide123. Discover practical tips for a balanced and healthy lifestyle.",
		tags: [
			"wellness",
			"health",
			"holisticliving",
			"wellnessguide",
			"ebook",
			"mindbodyspirit",
			"healthyhabits",
			"selfcare",
			"balance",
			"wellbeing",
			"mentalhealth",
			"lifestyle",
			"wellnesstips",
			"holistichealth",
			"selfhelp",
		],
		status: "Denied",
	},
	{
		id: 16,
		thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Software Development Bundle: Mastering Frameworks",
		author: {
			authorName: "CodeFrameworkMaster789",
			avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
			address: "789 Code Lane, FrameworkCity",
		},
		category: "Software Development",
		date: "2024-03-14",
		price: 59.99,
		description:
			"Become a framework master with this comprehensive software development bundle by CodeFrameworkMaster789. Master popular frameworks and enhance your coding skills.",
		tags: [
			"softwaredevelopment",
			"coding",
			"frameworks",
			"bundle",
			"webdevelopment",
			"codingguru",
			"codingcourse",
			"programming",
			"code",
			"javascript",
			"react",
			"angular",
			"vuejs",
			"developmenttools",
			"codingmaster",
		],
		status: "Approved",
	},
];

export const myOrderItems = [
	{
		id: 1,
		image: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Software Development Bundle: Mastering Frameworks",
		vendor: "MelodyMaestro456",
		price: 120,
		date: "2024-03-09",
		status: "Paid",
	},
	{
		id: 2,
		image: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Software Development Bundle: Mastering Frameworks",
		vendor: "MelodyMaestro456",
		price: 120,
		date: "2024-04-14",
		status: "Pending",
	},
	{
		id: 3,
		image: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Software Development Bundle: Mastering Frameworks",
		vendor: "MelodyMaestro456",
		price: 12.5,
		date: "2024-03-22",
		status: "Paid",
	},
	{
		id: 4,
		image: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Software Development Bundle: Mastering Frameworks",
		vendor: "MelodyMaestro456",
		price: 16.99,
		date: "2024-02-14",
		status: "Pending",
	},
	{
		id: 5,
		image: "https://dummyimage.com/365x245/a8a6a6/fff",
		title: "Software Development Bundle: Mastering Frameworks",
		vendor: "MelodyMaestro456",
		price: 120,
		date: "2024-03-18",
		status: "Paid",
	},
];

export const blogData = [
	{
		id: 1,
		thumbnail: "https://dummyimage.com/365x365/a8a6a6/fff",
		title: "Back sleep that back for our girl I but rather",
		author: "Ella Gross",
		category: "Classic Music",
		desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that.",
	},
	{
		id: 2,
		thumbnail: "https://dummyimage.com/365x365/a8a6a6/fff",
		title: "Back sleep that back for our girl I but rather",
		author: "Ella Gross",
		category: "Classic Music, Pop Music",
		desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that.",
	},
	{
		id: 3,
		thumbnail: "https://dummyimage.com/365x365/a8a6a6/fff",
		title: "Back sleep that back for our girl I but rather",
		author: "Ella Gross",
		category: "Classic Music",
		desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that.",
	},
	{
		id: 4,
		thumbnail: "https://dummyimage.com/365x365/a8a6a6/fff",
		title: "Back sleep that back for our girl I but rather",
		author: "Ella Gross",
		category: "Pop Music",
		desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that.",
	},
	{
		id: 5,
		thumbnail: "https://dummyimage.com/365x365/a8a6a6/fff",
		title: "Back sleep that back for our girl I but rather",
		author: "Ella Gross",
		category: "Music",
		desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that.",
	},
	{
		id: 6,
		thumbnail: "https://dummyimage.com/365x365/a8a6a6/fff",
		title: "Back sleep that back for our girl I but rather",
		author: "Ella Gross",
		category: "Pop Music",
		desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that.",
	},
];

export const recivedMessage = [
	{
		id: 1,
		time: "10:20 pm",
		date: "10 Jan 2024",
		message: "hi",
	},
	{
		id: 2,
		time: "10:20 pm",
		date: "10 Jan 2024",
		message: "Hello",
	},
	{
		id: 3,
		time: "10:24 pm",
		date: "10 Jan 2024",
		message: "How are you",
	},
	{
		id: 4,
		time: "10:20 pm",
		date: "10 Jan 2024",
		message: "nice to meet you too",
	},
];

export const vendorData = [
	{
		id: 1,
		name: "Ella Gross",
		image: "https://dummyimage.com/365x365/a8a6a6/fff",
		status: [
			{
				id: 1,
				option: "Painding",
			},
			{
				id: 2,
				option: "Approve",
			},
			{
				id: 3,
				option: "Reject",
			},
		],
	},
	{
		id: 2,
		name: "Ella Gross",
		image: "https://dummyimage.com/365x365/a8a6a6/fff",
		status: [
			{
				id: 1,
				option: "Pending",
			},
			{
				id: 2,
				option: "Approve",
			},
			{
				id: 3,
				option: "Reject",
			},
		],
	},
	{
		id: 3,
		name: "Ella Gross",
		image: "https://dummyimage.com/365x365/a8a6a6/fff",
		status: [
			{
				id: 1,
				option: "Painding",
			},
			{
				id: 2,
				option: "Approve",
			},
			{
				id: 3,
				option: "Reject",
			},
		],
	},
	{
		id: 4,
		name: "Ella Gross",
		image: "https://dummyimage.com/365x365/a8a6a6/fff",
		status: [
			{
				id: 1,
				option: "Painding",
			},
			{
				id: 2,
				option: "Approve",
			},
			{
				id: 3,
				option: "Reject",
			},
		],
	},
	{
		id: 5,
		name: "Ella Gross",
		image: "https://dummyimage.com/365x365/a8a6a6/fff",
		status: [
			{
				id: 1,
				option: "Painding",
			},
			{
				id: 2,
				option: "Approve",
			},
			{
				id: 3,
				option: "Reject",
			},
		],
	},
];

export const categoriesItems = [
	{
		id: 1,
		category: " Photo",
	},
	{
		id: 2,
		category: "Audio",
	},
	{
		id: 3,
		category: "Video",
	},
	{
		id: 4,
		category: "Software",
	},
	{
		id: 5,
		category: "AI Promt",
	},
	{
		id: 6,
		category: "Graphics",
	},
	{
		id: 7,
		category: "Document",
	},
];

export const aboutData = [
	{
		id: 1,
		desc: "Welcome to DiGiExplo, the global marketplace that connects digital content creators with enthusiasts and professionals from every corner of the world. Our mission is to empower individuals to share their unique stories and talents, while providing a one-stop destination for those seeking original and diverse digital content.",
	},
	{
		id: 2,
		desc: "At DiGiExplo, we believe that everyone has something special to offer. Be it a breathtaking photo from your village, a captivating video of daily life in your city, a mesmerizing piece of music you composed, an AI prompt or a set of music notes compiled into a PDF document – we provide a platform for you to showcase your creativity and share your passion with the world.",
	},
	{
		id: 3,
		desc: "Welcome to DiGiExplo, the global marketplace that connects digital content creators with enthusiasts and professionals from every corner of the world. Our mission is to empower individuals to share their unique stories and talents, while providing a one-stop destination for those seeking original and diverse digital content.",
	},
	{
		id: 4,
		desc: "For content seekers, DiGiExplo offers a treasure trove of inspiration and resources. Imagine finding the perfect photo to print, frame, and hang on your wall or discovering a stunning background video from a remote city that would otherwise be difficult to reach. Our extensive collection also includes captivating background music for podcasts and movies, catering to a wide array of creative needs.",
	},
	{
		id: 5,
		desc: "By bringing together creators and consumers, we foster a vibrant community that celebrates diversity, innovation, and the power of human expression. We are dedicated to providing a seamless and enjoyable experience for everyone involved, ensuring the highest standards of quality, originality, and customer service.",
	},
	{
		id: 6,
		desc: "Join us on this exciting journey and be a part of the ever-expanding world of DiGiExplo. Together, let's make the world of digital content more accessible, engaging, and inspiring than ever before.",
	},
	{
		id: 7,
		desc: "Welcome to DiGiExplo – your gateway to a universe of creativity and inspiration.",
	},
];

export const informationData = [
	{
		desc: "Personal Information: We may collect personal information you provide to us when you register for an account, update your account information, or submit Content to our Services. This information may include, but is not limited to, your name, email address, mailing address, phone number, and payment information.",
	},
	{
		desc: "Usage Information: When you access or use our Services, we may automatically collect information about your usage, such as your IP address, browser type, operating system, pages viewed, links clicked, and other similar information.",
	},
	{
		desc: "Cookies and Similar Technologies: We may use cookies, web beacons, and other similar technologies to collect and store information about your preferences and how you interact with our Services.",
	},
];

export const bigContentData = [
	{
		heading: "How We Use Your Information",
		subHeading:
			"We use the information we collect for various purposes, including to:",
		a: "Provide, maintain, and improve our Services;",
		b: "Process transactions and send you related information, such as confirmations and receipts;",
		c: "Communicate with you about promotions, news, and updates related to our Services;",
		d: "Monitor and analyze trends, usage, and activities in connection with our Services;",
		e: "Detect, prevent, and address technical issues and security risks;",
		f: "Personalize and improve your experience using our Services;",
		g: "Comply with applicable laws and regulations.",
	},
	{
		heading: "How We Share Your Information",
		subHeading: "We may share your information in the following circumstances:",
		a: "With your consent or at your direction;",
		b: "With third-party service providers that help us operate, provide, and maintain our Services, such as payment processors, hosting providers, and analytics providers;",
		c: "In response to a legal request, such as a subpoena, court order, or government demand;",
		d: "In connection with a merger, acquisition, reorganization, or sale of our business, assets, or equity; ",
		e: "If we believe it is necessary to investigate, prevent, or take action regarding illegal activities, suspected fraud, violations of our Terms and Conditions, or other situations involving potential threats to the safety or legal rights of any person or entity.",
	},
];

export const smallContentData = [
	{
		heading: "Security",
		desc: "We take reasonable measures to protect the security of your personal information. However, no method of transmission over the internet or electronic storage is completely secure, and we cannot guarantee the absolute security of your personal information.",
	},
	{
		heading: "Third-Party Links",
		desc: "Our Services may contain links to third-party websites or services. We are not responsible for the privacy practices or the content of these third-party websites or services, and your interactions with them are governed by their respective privacy policies.",
	},
	{
		heading: "International Data Transfers",
		desc: "Your personal information may be transferred to, stored, and processed in countries other than the country in which you initially provided the information. By using our Services, you consent to the transfer, storage, and processing of your personal information in such countries.",
	},
	{
		heading: "Children's Privacy (continued)",
		desc: "Our Services are not intended for individuals under the age of 18. We do not knowingly collect personal information from children under 18, and if we become aware that we have collected personal information from a child under 18, we will take steps to remove that information and delete the child's account.",
	},
	{
		heading: "Your Rights and Choices",
		desc: "Depending on your jurisdiction, you may have certain rights regarding the personal information we collect and hold about you. These rights may include the right to access, correct, or delete your personal information, as well as the right to object to or restrict certain types of processing of your personal information. To exercise these rights, please contact us at [Your Email Address].",
	},
	{
		heading: "Changes to This Privacy Policy",
		desc: "We reserve the right to update or change our Privacy Policy at any time, in our sole discretion. We will provide reasonable notice of any material changes to the Privacy Policy, either by posting the updated Privacy Policy on our website or through other means of communication. Your continued use of our Services after any changes to the Privacy Policy constitutes your acceptance of the new Privacy Policy. If you do not agree to the updated Privacy Policy, you must stop using our Services.",
	},
];

export const TandCData = [
	{
		heading: "Eligibility",
		desc: "To use our Services, you must be at least 18 years old and have the legal capacity to enter into a binding contract. By using our Services, you represent and warrant that you meet these eligibility requirements.",
	},
	{
		heading: "User Accounts",
		desc: "To access some features of our Services, you may be required to register for an account. You agree to provide accurate, current, and complete information during the registration process and to update your information as necessary. You are responsible for safeguarding your password and for any activities or actions taken under your account. Notify us immediately if you suspect unauthorized use of your account.",
	},
	{
		heading: "Content Submission and Ownership",
		desc: "By submitting any digital content, including but not limited to photos, movies, sounds, and other media files (collectively, Content), you represent and warrant that:",
		descChild:
			"You own or have the necessary licenses, rights, consents, and permissions to the Content;",
		descChild2:
			"The Content is original and does not infringe, misappropriate, or violate any third party's intellectual property rights, privacy rights, or any other legal or moral rights;",
		descChild3:
			"The Content does not contain any material that is defamatory, obscene, offensive, or otherwise unlawful;",
		descChild4:
			"You have obtained any necessary releases and permissions from any individuals or entities depicted or referenced in the Content.",
		desc2:
			"You retain all ownership rights in your Content. However, by submitting Content to ",
	},
	{
		heading: "Termination",
		desc: "We reserve the right, in our sole discretion, to suspend or terminate your account and access to our Services at any time, with or without notice, for any reason, including but not limited to violation of these Terms.",
	},
	{
		heading: "Governing Law and Jurisdiction",
		desc: "These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions. Any disputes arising out of or relating to these Terms shall be subject to the exclusive jurisdiction of the courts located in [Your Jurisdiction].",
	},
	{
		heading: "Changes to These Terms",
		desc: "We reserve the right to modify or replace these Terms at any time, in our sole discretion. We will provide reasonable notice of any material changes to the Terms, either by posting the updated Terms on our website or through other means of communication. Your continued use of our Services after any changes to the Terms constitutes your acceptance of the new Terms. If you do not agree to the updated Terms, you must stop using our Services.",
	},
	{
		heading: "Miscellaneous",
		desc: "If any provision of these Terms is found to be invalid, illegal, or unenforceable by a court of competent jurisdiction, the remaining provisions shall remain in full force and effect. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. These Terms constitute the entire agreement between us regarding our Services, and supersede and replace any prior agreements we might have had between us regarding the Services.",
	},
];

export const productItems = [
  {
    id: 1,
    image: "https://dummyimage.com/365x365/a8a6a6/fff",
    productName: "Digital Art Collection",
    category: "Audio",
    price: 50,
  },
  {
    id: 2,
    image: "https://dummyimage.com/365x365/a8a6a6/fff",
    productName: "Photography Bundle: Captured Moments",
    category: "Video",
    price: 60.39,
  }
]

export const vendorItems = [
  {
    _id: "1",
    profileImg: "https://dummyimage.com/365x365/a8a6a6/fff",
    firstName: "Boltu",
    email: "boltu@gmail.com",
    companyName: "Boltu SDN BHD.",
    website: "https//:www.boltu.com",
    status: "Approved"
  },
  {
    _id: "2",
    profileImg: "https://dummyimage.com/365x365/a8a6a6/fff",
    firstName: "Boltu",
    email: "boltu@gmail.com",
    companyName: "Boltu SDN BHD.",
    website: "https//:www.boltu.com",
    status: "Approved"
  },
  {
    _id: "3",
    profileImg: "https://dummyimage.com/365x365/a8a6a6/fff",
    firstName: "Boltu",
    email: "boltu@gmail.com",
    companyName: "Boltu SDN BHD.",
    website: "https//:www.boltu.com",
    status: "Approved"
  },
  {
    _id: "4",
    profileImg: "https://dummyimage.com/365x365/a8a6a6/fff",
    firstName: "Boltu",
    email: "boltu@gmail.com",
    companyName: "Boltu SDN BHD.",
    website: "https//:www.boltu.com",
    status: "Approved"
  },
]
