export const tags = [
  "art",
  "digital",
  "creative",
  "illustration",
  "design",
  "modern",
  "unique",
  "gallery",
  "imagination",
  "expression",
  "colorful",
  "digitalart",
  "collection",
  "artist",
  "artistic",
  "coding",
  "programming",
  "javascript",
  "python",
  "codingadventures",
  "code",
  "webdevelopment",
  "codingcommunity",
  "ebook",
  "learntocode",
  "codinglife",
  "development",
  "technology",
  "codingtips",
  "software",
  "music",
  "album",
  "harmony",
  "melody",
  "sound",
  "musical",
  "waves",
  "composition",
  "instrumental",
  "audio",
  "melodic",
  "musician",
  "harmonicwaves",
  "artist",
  "musiclover",
  "photography",
  "photo",
  "capture",
  "snapshot",
  "photographer",
  "bundle",
  "picture",
  "moment",
  "visual",
  "artistic",
  "gallery",
  "creative",
  "photograph",
  "collection",
  "image",
  "scifi",
  "sciencefiction",
  "adventure",
  "ebook",
  "space",
  "future",
  "exploration",
  "aliens",
  "technology",
  "imagination",
  "science",
  "fiction",
  "author",
  "book",
  "adventures",
  "webdevelopment",
  "html",
  "css",
  "codingcourse",
  "codingtutorial",
  "webdesign",
  "programming",
  "code",
  "frontend",
  "webdeveloper",
  "htmlcss",
  "webdev",
  "tutorial",
  "webmaster",
  "coding",
  "digitalmarketing",
  "marketing",
  "onlinepresence",
  "guide",
  "branding",
  "socialmedia",
  "strategy",
  "digitalstrategy",
  "marketingtips",
  "business",
  "onlinebranding",
  "promotion",
  "guidebook",
  "marketingexpert",
  "brandboost",
  "cooking",
  "culinary",
  "cookbook",
  "recipes",
  "chef",
  "food",
  "delicious",
  "cuisine",
  "gourmet",
  "flavorful",
  "homemade",
  "foodie",
  "kitchen",
  "culinaryarts",
  "tasty",
  "fitness",
  "healthyliving",
  "workout",
  "exercise",
  "wellness",
  "guide",
  "fitlife",
  "health",
  "nutrition",
  "fitnesstips",
  "body",
  "fitnessjourney",
  "healthyhabits",
  "lifestyle",
  "wellbeing",
  "travel",
  "photography",
  "wanderlust",
  "worldwonders",
  "explore",
  "adventure",
  "collection",
  "travelphotographer",
  "visualjourney",
  "landscape",
  "wondersoftheworld",
  "photocollection",
  "discover",
  "globetrotter",
  "languagelearning",
  "polyglot",
  "languages",
  "linguistics",
  "bundle",
  "multilingual",
  "languagecourse",
  "linguist",
  "communication",
  "multilanguage",
  "languagestudy",
  "polyglotism",
  "linguisticbundle",
  "learnlanguages",
  "communication",
  "selfcare",
  "wellness",
  "mindfulness",
  "guide",
  "health",
  "mentalhealth",
  "bodycare",
  "relaxation",
  "wellnessguru",
  "zen",
  "stressrelief",
  "mindbodysoul",
  "mindful",
  "holistic",
  "wellbeing",
  "fashion",
  "fashiondesign",
  "style",
  "course",
  "design",
  "creativity",
  "fashionista",
  "clothing",
  "trendy",
  "expressyourself",
  "creativeexpression",
  "designcourse",
  "fashionlover",
  "stylish",
  "couture",
  "languagelearning",
  "polyglot",
  "languages",
  "linguistics",
  "bundle",
  "multilingual",
  "languagecourse",
  "linguist",
  "communication",
  "multilanguage",
  "languagestudy",
  "polyglotism",
  "linguisticbundle",
  "learnlanguages",
  "communication",
];

export const categories = [
  "Digital Art",
  "Programming",
  "Music",
  "Photography",
  "Science Fiction",
  "Web Development",
  "Digital Marketing",
  "Cooking",
  "Fitness",
  "Travel",
  "Language Learning",
  "Wellness",
  "Fashion",
  "Health & Wellness",
  "Software Development",
];

export const products = [
  {
    id: 1,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Digital Art Collection",
    author: {
      authorName: "CreativeArtist123",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "123 Art Street, Imaginaria",
    },
    category: "Digital Art",
    date: "2024-02-03",
    price: 19.99,
    description:
      "Explore a stunning collection of digital artworks created by CreativeArtist123. Each piece is a unique expression of creativity.",
    tags: [
      "art",
      "digital",
      "creative",
      "illustration",
      "design",
      "modern",
      "unique",
      "gallery",
      "imagination",
      "expression",
      "colorful",
      "digitalart",
      "collection",
      "artist",
      "artistic",
    ],
    status: "Pending",
  },
  {
    id: 2,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Ebook: Coding Adventures",
    author: {
      authorName: "CodeExplorer789",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "789 Code Lane, Algorithm City",
    },
    category: "Programming",
    date: "2024-02-05",
    price: 14.99,
    description:
      "Embark on coding adventures with this comprehensive ebook by CodeExplorer789. Learn new programming techniques and improve your coding skills.",
    tags: [
      "coding",
      "programming",
      "javascript",
      "python",
      "codingadventures",
      "code",
      "webdevelopment",
      "codingcommunity",
      "ebook",
      "learntocode",
      "codinglife",
      "development",
      "technology",
      "codingtips",
      "software",
    ],
    status: "Approved",
  },
  {
    id: 3,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Music Album: Harmonic Waves",
    author: {
      authorName: "MelodyMaestro456",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "456 Melody Street, Harmony Town",
    },
    category: "Music",
    date: "2024-02-08",
    price: 24.99,
    description:
      "Immerse yourself in the soothing melodies of Harmonic Waves, a music album crafted by MelodyMaestro456. Experience a journey through various musical genres.",
    tags: [
      "music",
      "album",
      "harmony",
      "melody",
      "sound",
      "musical",
      "waves",
      "composition",
      "instrumental",
      "audio",
      "melodic",
      "musician",
      "harmonicwaves",
      "artist",
      "musiclover",
    ],
    status: "Denied",
  },
  {
    id: 4,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Photography Bundle: Captured Moments",
    author: {
      authorName: "SnapshotMaster789",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "789 Shutter Street, Pictureville",
    },
    category: "Photography",
    date: "2024-02-10",
    price: 29.99,
    description:
      "Discover a stunning collection of high-quality photographs in the Captured Moments bundle by SnapshotMaster789. Each image tells a unique story.",
    tags: [
      "photography",
      "photo",
      "capture",
      "snapshot",
      "photographer",
      "bundle",
      "picture",
      "moment",
      "visual",
      "artistic",
      "gallery",
      "creative",
      "photograph",
      "collection",
      "image",
    ],
    status: "Approved",
  },
  {
    id: 5,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Ebook: Sci-Fi Adventures",
    author: {
      authorName: "SciFiExplorer456",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "456 Future Lane, Sci-Fi City",
    },
    category: "Science Fiction",
    date: "2024-02-12",
    price: 16.99,
    description:
      "Embark on thrilling sci-fi adventures with this captivating ebook by SciFiExplorer456. Dive into futuristic worlds and explore the unknown.",
    tags: [
      "scifi",
      "sciencefiction",
      "adventure",
      "ebook",
      "space",
      "future",
      "exploration",
      "aliens",
      "technology",
      "imagination",
      "science",
      "fiction",
      "author",
      "book",
      "adventures",
    ],
    status: "Pending",
  },
  {
    id: 6,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Web Development Course: Mastering HTML & CSS",
    author: {
      authorName: "CodeMaster789",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "789 Code Lane, Webville",
    },
    category: "Web Development",
    date: "2024-02-15",
    price: 49.99,
    description:
      "Learn the essentials of web development with this comprehensive course by CodeMaster789. Master HTML and CSS to build stunning websites.",
    tags: [
      "webdevelopment",
      "html",
      "css",
      "codingcourse",
      "codingtutorial",
      "webdesign",
      "programming",
      "code",
      "frontend",
      "webdeveloper",
      "htmlcss",
      "webdev",
      "tutorial",
      "webmaster",
      "coding",
    ],
    status: "Denied",
  },
  {
    id: 7,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Digital Marketing Guide: Boost Your Online Presence",
    author: {
      authorName: "MarketingPro123",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "123 Market Street, BrandCity",
    },
    category: "Digital Marketing",
    date: "2024-02-18",
    price: 34.99,
    description:
      "Enhance your online presence with this comprehensive digital marketing guide by MarketingPro123. Learn proven strategies to boost your brand.",
    tags: [
      "digitalmarketing",
      "marketing",
      "onlinepresence",
      "guide",
      "branding",
      "socialmedia",
      "strategy",
      "digitalstrategy",
      "marketingtips",
      "business",
      "onlinebranding",
      "promotion",
      "guidebook",
      "marketingexpert",
      "brandboost",
    ],
    status: "Pending",
  },
  {
    id: 8,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Cookbook: Culinary Delights",
    author: {
      authorName: "GourmetChef456",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "456 Culinary Lane, Flavorville",
    },
    category: "Cooking",
    date: "2024-02-20",
    price: 19.99,
    description:
      "Explore the world of culinary delights with this exquisite cookbook by GourmetChef456. Discover mouth-watering recipes and culinary secrets.",
    tags: [
      "cooking",
      "culinary",
      "cookbook",
      "recipes",
      "chef",
      "food",
      "delicious",
      "cuisine",
      "gourmet",
      "flavorful",
      "homemade",
      "foodie",
      "kitchen",
      "culinaryarts",
      "tasty",
    ],
    status: "Approved",
  },

  {
    id: 9,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Fitness Guide: Healthy Living Journey",
    author: {
      authorName: "FitLifestyle789",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "789 Wellness Street, FitCity",
    },
    category: "Fitness",
    date: "2024-02-23",
    price: 24.99,
    description:
      "Embark on a journey to a healthier lifestyle with this fitness guide by FitLifestyle789. Discover effective workout routines and nutrition tips.",
    tags: [
      "fitness",
      "healthyliving",
      "workout",
      "exercise",
      "wellness",
      "guide",
      "fitlife",
      "health",
      "nutrition",
      "fitnesstips",
      "body",
      "fitnessjourney",
      "healthyhabits",
      "lifestyle",
      "wellbeing",
    ],
    status: "Denied",
  },
  {
    id: 10,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Travel Photography Collection: World Wonders",
    author: {
      authorName: "WanderlustExplorer123",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "123 Explorer Avenue, Wanderland",
    },
    category: "Travel",
    date: "2024-02-26",
    price: 39.99,
    description:
      "Embark on a visual journey around the world with this stunning travel photography collection by WanderlustExplorer123. Explore iconic world wonders through captivating images.",
    tags: [
      "travel",
      "photography",
      "wanderlust",
      "worldwonders",
      "explore",
      "adventure",
      "collection",
      "travelphotographer",
      "visualjourney",
      "landscape",
      "wondersoftheworld",
      "photocollection",
      "discover",
      "globetrotter",
    ],
    status: "Approved",
  },
  {
    id: 11,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Language Learning Bundle: Master Multiple Languages",
    author: {
      authorName: "PolyglotMaster789",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "789 Linguistics Lane, Polyglot City",
    },
    category: "Language Learning",
    date: "2024-02-29",
    price: 44.99,
    description:
      "Become a polyglot with this language learning bundle by PolyglotMaster789. Master multiple languages and unlock new opportunities.",
    tags: [
      "languagelearning",
      "polyglot",
      "languages",
      "linguistics",
      "bundle",
      "multilingual",
      "languagecourse",
      "linguist",
      "communication",
      "multilanguage",
      "languagestudy",
      "polyglotism",
      "linguisticbundle",
      "learnlanguages",
      "communication",
    ],
    status: "Pending",
  },
  {
    id: 12,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Self-Care Guide: Nurturing Your Mind and Body",
    author: {
      authorName: "WellnessGuru456",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "456 Serenity Street, ZenVille",
    },
    category: "Wellness",
    date: "2024-03-02",
    price: 29.99,
    description:
      "Prioritize self-care with this comprehensive guide by WellnessGuru456. Nurture your mind and body with practical tips and mindful practices.",
    tags: [
      "selfcare",
      "wellness",
      "mindfulness",
      "guide",
      "health",
      "mentalhealth",
      "bodycare",
      "relaxation",
      "wellnessguru",
      "zen",
      "stressrelief",
      "mindbodysoul",
      "mindful",
      "holistic",
      "wellbeing",
    ],
    status: "Denied",
  },
  {
    id: 13,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Fashion Design Course: Unleash Your Creativity",
    author: {
      authorName: "Fashionista123",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "123 Style Avenue, FashionCity",
    },
    category: "Fashion",
    date: "2024-03-05",
    price: 54.99,
    description:
      "Discover the world of fashion design with this engaging course by Fashionista123. Unleash your creativity and express your unique style.",
    tags: [
      "fashion",
      "fashiondesign",
      "style",
      "course",
      "design",
      "creativity",
      "fashionista",
      "clothing",
      "trendy",
      "expressyourself",
      "creativeexpression",
      "designcourse",
      "fashionlover",
      "stylish",
      "couture",
    ],
    status: "Pending",
  },
  {
    id: 14,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Digital Course: Photography Fundamentals",
    author: {
      authorName: "PhotoEnthusiast789",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "789 Shutter Lane, PhotoCity",
    },
    category: "Photography",
    date: "2024-03-08",
    price: 39.99,
    description:
      "Master the fundamentals of photography with this comprehensive digital course by PhotoEnthusiast789. Learn essential techniques and improve your photography skills.",
    tags: [
      "photography",
      "course",
      "fundamentals",
      "digitalcourse",
      "photoenthusiast",
      "photographyeducation",
      "learning",
      "phototechniques",
      "skillbuilding",
      "visualart",
      "photo",
      "photographer",
      "education",
      "digitallearning",
      "camera",
    ],
    status: "Approved",
  },
  {
    id: 15,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Health and Wellness Ebook: Holistic Living",
    author: {
      authorName: "WellnessGuide123",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "123 Serenity Street, WellnessVille",
    },
    category: "Health & Wellness",
    date: "2024-03-11",
    price: 18.99,
    description:
      "Embark on a journey of holistic living with this health and wellness ebook by WellnessGuide123. Discover practical tips for a balanced and healthy lifestyle.",
    tags: [
      "wellness",
      "health",
      "holisticliving",
      "wellnessguide",
      "ebook",
      "mindbodyspirit",
      "healthyhabits",
      "selfcare",
      "balance",
      "wellbeing",
      "mentalhealth",
      "lifestyle",
      "wellnesstips",
      "holistichealth",
      "selfhelp",
    ],
    status: "Denied",
  },
  {
    id: 16,
    thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
    title: "Software Development Bundle: Mastering Frameworks",
    author: {
      authorName: "CodeFrameworkMaster789",
      avatar: "https://dummyimage.com/90x90/a8a6a6/fff",
      address: "789 Code Lane, FrameworkCity",
    },
    category: "Software Development",
    date: "2024-03-14",
    price: 59.99,
    description:
      "Become a framework master with this comprehensive software development bundle by CodeFrameworkMaster789. Master popular frameworks and enhance your coding skills.",
    tags: [
      "softwaredevelopment",
      "coding",
      "frameworks",
      "bundle",
      "webdevelopment",
      "codingguru",
      "codingcourse",
      "programming",
      "code",
      "javascript",
      "react",
      "angular",
      "vuejs",
      "developmenttools",
      "codingmaster",
    ],
    status: "Approved",
  },
];


export const myOrderItems = [
   {
      id: 1,
      image: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Software Development Bundle: Mastering Frameworks",
      vendor: "MelodyMaestro456",
      price: 120,
      date: "2024-03-09",
      status: "Paid"
   },
   {
      id: 2,
      image: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Software Development Bundle: Mastering Frameworks",
      vendor: "MelodyMaestro456",
      price: 120,
      date: "2024-04-14",
      status: "Pending"
   },
   {
      id: 3,
      image: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Software Development Bundle: Mastering Frameworks",
      vendor: "MelodyMaestro456",
      price: 12.50,
      date: "2024-03-22",
      status: "Paid"
   },
   {
      id: 4,
      image: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Software Development Bundle: Mastering Frameworks",
      vendor: "MelodyMaestro456",
      price: 16.99,
      date: "2024-02-14",
      status: "Pending"
   },
   {
      id: 5,
      image: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Software Development Bundle: Mastering Frameworks",
      vendor: "MelodyMaestro456",
      price: 120,
      date: "2024-03-18",
      status: "Paid"
   }
]


export const blogData = [
   {
      id: 1,
      thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Back sleep that back for our girl I but rather",
      author: "Ella Gross",
      category: "Classic Music",
      desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that."
   },
   {
      id: 2,
      thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Back sleep that back for our girl I but rather",
      author: "Ella Gross",
      category: "Classic Music, Pop Music",
      desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that."
   },
   {
      id: 3,
      thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Back sleep that back for our girl I but rather",
      author: "Ella Gross",
      category: "Classic Music",
      desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that."
   },
   {
      id: 4,
      thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Back sleep that back for our girl I but rather",
      author: "Ella Gross",
      category: "Pop Music",
      desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that."
   },
   {
      id: 5,
      thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Back sleep that back for our girl I but rather",
      author: "Ella Gross",
      category: "Music",
      desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that."
   },
   {
      id: 6,
      thumbnail: "https://dummyimage.com/365x245/a8a6a6/fff",
      title: "Back sleep that back for our girl I but rather",
      author: "Ella Gross",
      category: "Pop Music",
      desc: "In for display, free for she my century employed are her be of problem. Does been the of one. Own live their location greater, parents’. Carpeting me a look was. Picture be their the project it and made go you’d much of being spot. Everyone the above to report that."
   }
]
