import Table from "@/components/Dashboard/Table";
import { Metadata } from "next";
import DashboardHeader from "./DashboardHeader";

export const metadata: Metadata = {
	title: "My Order Items | Digi Explo",
	description: "Generated by create next app",
};

const MyOrderItems = () => {
	return (
		<div>
			<DashboardHeader
				currentPage="my ordered items"
				title="Order History"
				url="dashboard"
			/>
			<div className="px-8 md:px-10">
				<Table />
			</div>
		</div>
	);
};

export default MyOrderItems;
