import Table from "@/components/Dashboard/Table";
import { Metadata } from "next";
import DashboardHeader from "./DashboardHeader";

export const metadata: Metadata = {
  title: "My Order Items | Digi Explo",
  description: "Generated by create next app",
};

const MyOrderItems = () => {
  return (
    <div>
      <DashboardHeader
        currentPage="my ordered items"
        title="Order History"
        url="dashboard"
      />
      <div className="px-8 md:px-10">
        <div className="p-8 md:p-10 rounded-md box-shadow border border-[#F1F1F4] max-w-7xl">
          <div className="mb-5">
            <h3 className="text-textColor text-[17px] font-semibold">
              Product Stats
            </h3>
            <p className="text-[#99a1b7] font-medium">My Order items</p>
          </div>
          <Table />
        </div>
      </div>
    </div>
  );
};

export default MyOrderItems;
