import React from "react";
import { Metadata } from "next";
import PageContent from "@/components/Dashboard/Password/PageContent";
import DashboardHeader from "@/components/Dashboard/DashboardHeader";

export const metadata: Metadata = {
  title: "Change Password | Digi Explo",
  description: "Generated by create next app",
};

const ChangePassword = () => {
  return (
    <>
      <DashboardHeader
        currentPage="change password"
        title="Change Password"
        url="dashboard"
      />
      <PageContent />
    </>
  );
};

export default ChangePassword;
