import React from "react";
import { Metadata } from "next";
import PageContent from "@/components/Dashboard/Password/PageContent";

export const metadata: Metadata = {
	title: "Change Password | Digi Explo",
	description: "Generated by create next app",
};

const ChangePassword = () => {
	return (
		<div className="mx-auto md:px-0 w-full z-10">
			<PageContent />
		</div>
	);
};

export default ChangePassword;
