import React from 'react'
import { Metadata } from 'next';
import Container from '@/components/Container'
import SingleBlogBanner from '@/components/SingleBlogPage/SingleBlogBanner';
import SingleBlogContent from '@/components/SingleBlogPage/SingleBlogContent';

export const metadata: Metadata = {
   title: "Blog Details | Digi Expo",
   description: "Generated by create next app",
};


const BlogDetails = () => {
   return (
      <Container>
         <SingleBlogBanner />
         <SingleBlogContent />
      </Container>
   )
}

export default BlogDetails;