import React from "react";
import { Metadata } from "next";
import Footer from "@/components/Footer/Footer";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
	title: "Home | Digi Expo",
	description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
	return (
		<div className="flex gap-2">
			<Sidebar />
			<div className="w-full bg-[#FEFFFF] mr-auto">
				<Navbar />
				{children}
				<Footer />
			</div>
		</div>
	);
};

export default Layout;
