import React from "react";
import { Metadata } from "next";
import BlogBanner from "@/components/BlogPage/BlogBanner";
import BlogContent from "@/components/BlogPage/BlogContent";
import Container from "@/components/Container";

export const metadata: Metadata = {
  title: "Blog | Digi Expo",
  description: "Generated by create next app",
};

const BlogPage = () => {
  return (
    <Container>
      <BlogBanner />
      {/* <BlogContent /> */}
    </Container>
  );
};

export default BlogPage;
