import DashboardHome from "@/components/Dashboard/DashboardHome";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profile | Digi Explo",
  description: "Generated by create next app",
};

const Dashboard = () => {
  return <DashboardHome />;
};

export default Dashboard;
