import React from "react";
import { Metadata } from "next";
import PageContent from "@/components/Dashboard/Password/PageContent";

export const metadata: Metadata = {
	title: "Profile | Digi Explo",
	description: "Generated by create next app",
};

const Dashboard = () => {
	return <div>{/*  */}</div>;
};

export default Dashboard;
