import React from "react";
import { Metadata } from "next";
import PageContent from "@/components/ProfileSettingPage/PageContent";

export const metadata: Metadata = {
   title: "Profile | Digi Expo",
   description: "Generated by create next app",
};

const Dashboard = () => {
	return (
		<div>
         <PageContent />
		</div>
	);
};

export default Dashboard;
