import React from "react";
import { Metadata } from "next";
import Container from "@/components/Container";

export const metadata: Metadata = {
   title: "My Order Items | Digi Explo",
   description: "Generated by create next app",
};

const ProfileSettingPage = () => {

	return (
		<Container>
			<div className="flex flex-col mt-5">
            <table>
               <thead className="text-center">
                  <tr className="divide-x-2 divide-neutral-400  text-white text-sm uppercase font-medium bg-gray-400">
                     <th
                        scope="col"
                        className="px-5 py-3"
                     >
                        Product Image
                     </th>
                     <th
                        scope="col"
                        className="px-5 py-3"
                     >
                        Product Title
                     </th>
                     <th
                        scope="col"
                        className="px-5 py-3"
                     >
                        Autor
                     </th>
                     <th
                        scope="col"
                        className="px-5 py-3"
                     >
                        Product Price
                     </th>
                     <th
                        scope="col"
                        className="px-5 py-3"
                     >
                        Product Category
                     </th>
                     <th
                        className="px-5 py-3"
                        scope="col"
                     >
                        Status
                     </th>
                  </tr>
               </thead>
            </table>
         </div>
		</Container>
	);
};

export default ProfileSettingPage;
