import React from "react";
import { Metadata } from "next";
import Container from "@/components/Container";
import Table from "@/components/Dashboard/Table";

export const metadata: Metadata = {
   title: "My Order Items | Digi Explo",
   description: "Generated by create next app",
};

const MyOrderItems = () => {

	return (
		<div className="mx-auto md:px-0 w-full z-10">
			<div className='p-8 md:p-10 rounded-md box-shadow border border-[#F1F1F4] max-w-7xl w-full mx-auto'>
            <div className="mb-5">
               <h3 className="text-textColor text-[17px] font-semibold">Product Stats</h3>
               <p className="text-[#99a1b7] font-medium">My order items</p>
            </div>
            <Table />
         </div>
		</div>
	);
};

export default MyOrderItems;
