import MyOrderItems from "@/components/Dashboard/MyOrderItems";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "My Order Items | Digi Explo",
  description: "Generated by create next app",
};

const MyOrderPage = () => {
  return (
    <div>
      <MyOrderItems />
    </div>
  );
};

export default MyOrderPage;
